### PR TITLE
all warnings added to wald test

### PR DESCRIPTION
**Pull request by jgitr**

### CODE REVIEW

**Comment by jgitr** [comment]
changed to stop instead of warning

**Review by gunthecl — COMMENTED** [review]
Fixed some bugs in the Wald test. Please run a couple of test to make sure it works now

**Review by gunthecl — DISMISSED** [review]
FINAL CHANGES - ready to merge
- added missing checks (spec should not be logiccal or contain zeros)
- deleted wrong warnings message (not testing joint signif) -> since we transform all numerical values, we are conduction a joint significances test

**Review by gunthecl — APPROVED** [review]
Looks good

**Pull request merged**
