### PR TITLE
Quantlet1

### PR DESCRIPTION
**Pull request by phinguyen44**
1. Julian - updated Quantlet 1 with package install instructions
2. Claudia - updated readme
3. Phi - updated to fit style guide

A branch where we all made changes! WOAAH. WAY TO COLLABORATE TEAM 👍 💯

### CODE REVIEW

**Review by gunthecl — DISMISSED** [review]
Something is not right with the package commands. We can have a look at this later on.

**Comment by phinguyen44** [comment]
Hey @jgitr, can you explain your steps in the install + load packages changes that you've made in the `ReadAndClean.R` code? It works fine for me but it seems particularly long and winded and maybe unnecessary?

**Comment by jgitr** [comment]
sure :) it's divided as follows:
- define necessary packages
- check if these packages exist already on the target computer, install those that are missing
- if the user agrees, detach all unnecessary packages to prevent interference
- else continue with warning
- load all specified packages (since they are all installed now)
True, it is kind of long and winded. But detaching unused packages has proven itself quite useful to me, though. I don't think they would start every time with a clean session when they check out our code.

**Comment by gunthecl** [comment]
I have issues using the package functions in the code. I doesn't work for me.

**Comment by jgitr** [comment]
@gunthecl where exactly does the code break?
Spontaneously I would guess that it may be due to a different Sys.getenv() order (mac)

**Comment by phinguyen44** [comment]
@jgitr I also see this message the first time I run it, but never thereafter:

bildschirmfoto 2017-11-28 um 17 45 21

Also what's kind of annoying with the `menu` utils in the `userChoice` object is that I no longer can run all the code at once, but have to do it line by line. Is there perhaps a better alternative?

**Comment by jgitr** [comment]
@phister Will investigate that warning. Concerning the line-by-line: do you have graphics.off()? For me the code stops and delays execution until a menu selection has been made.

**Comment by phinguyen44** [comment]
A lot of changes in this update. I'll provide brief details here.

1. **Setting working path**: Changed so that easySHARE data set is moved into the root folder and not in /Data subfolder based off Claudia's suggestion. It should make running the code smoother. Also added more notes to setting working directory so that it's easier for people to understand (again based off Claudia's suggestions). Now ideally a user must only change the working directory in line 7 and everything works fine.
2. **Loading and installing packages**: @jgitr, I've removed your code for now since it will not run unless XQuartz is not natively installed on new Mac OS's. All I've kept is the "install if not loaded part". If you want to still include that, you can create a separate branch. For the time being, I want to be able to merge this branch ASAP so we can start other quantlets.
3. **Changed variables to correct type**: For example, age and gender are now factors. This ensures that the `standardize` function doesn't accidentally pick them up and standardize them.
4. **Split data frames into country / gender combinations for regression**: In the paper, regression is run for each gender and for each country. To enable that, I split the `df.reg` data frame into data frames in the `df.split` list and converted all the variables into dummy variables (except the numeric variables, obviously). 

If you want to see these changes on your local machine, run `git pull --rebase`.

**Review by jgitr — COMMENTED** [review]
Great progress. We should replace `require` with `library`, though. 
Removing the detachment part is probably better. Maybe I'll find a replacement. Elsewise we should contemplate working with explicit function calls (`dplyr::..`). But that's rather something to keep track of in general, no need to delay approval :)

**Review by jgitr — DISMISSED** [review]
details in comment before

**Comment by phinguyen44** [comment]
@jgitr good catch. just changed it.

**Pull request merged**
